services:
  - type: web
    name: sia-inventario
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn core.wsgi:application --workers 2 --timeout 300"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: "False"
