# Generated by Django 6.0.6 on 2026-08-04 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asignacionespecial_detalleasignacionespecial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo_solicitud', models.CharField(choices=[('Ayuda Médica', 'Ayuda Médica'), ('Enseres / Ayuda Social', 'Enseres / Ayuda Social'), ('Donación de Medicamentos', 'Donación de Medicamentos'), ('Soporte Técnico / Tránsito', 'Soporte Técnico / Tránsito'), ('Asesoría Jurídica', 'Asesoría Jurídica'), ('Otro', 'Otro')], default='Enseres / Ayuda Social', max_length=100)),
                ('descripcion_solicitud', models.TextField()),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20)),
                ('status', models.CharField(choices=[('Recibida', 'Recibida'), ('En Proceso', 'En Proceso'), ('Aprobada', 'Aprobada'), ('Entregada', 'Entregada'), ('Rechazada', 'Rechazada')], default='Recibida', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observaciones_seguimiento', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Atención al Ciudadano',
                'verbose_name_plural': 'Solicitudes de Atención al Ciudadano',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
