# Generated by Django 6.0.6 on 2026-08-04 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroauditoria',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de Auditoría', 'verbose_name_plural': 'Registros de Auditoría'},
        ),
        migrations.RemoveField(
            model_name='registroauditoria',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='registroauditoria',
            name='ip_origen',
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='asignacionespecial',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='modulo',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudciudadano',
            name='cedula',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudciudadano',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='solicitudciudadano',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], db_index=True, default='Media', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudciudadano',
            name='status',
            field=models.CharField(choices=[('Recibida', 'Recibida'), ('En Proceso', 'En Proceso'), ('Aprobada', 'Aprobada'), ('Entregada', 'Entregada'), ('Rechazada', 'Rechazada')], db_index=True, default='Recibida', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudciudadano',
            name='tipo_solicitud',
            field=models.CharField(choices=[('Ayuda Médica', 'Ayuda Médica'), ('Enseres / Ayuda Social', 'Enseres / Ayuda Social'), ('Donación de Medicamentos', 'Donación de Medicamentos'), ('Soporte Técnico / Tránsito', 'Soporte Técnico / Tránsito'), ('Asesoría Jurídica', 'Asesoría Jurídica'), ('Otro', 'Otro')], db_index=True, default='Enseres / Ayuda Social', max_length=100),
        ),
    ]
