# Generated by Django 6.0.6 on 2026-08-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_registroauditoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='permisos_detalle',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
