# Generated by Django 6.0.6 on 2026-08-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilusuario_permisos_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='ALCALDÍA SOCIAL / DIRECCIÓN DE ATENCIÓN CIUDADANA', max_length=255)),
                ('subtitulo_institucion', models.CharField(default='SIA Web - Sistema Institucional de Atención e Inventario', max_length=255)),
                ('rif', models.CharField(default='G-20000000-0', max_length=50)),
                ('direccion', models.TextField(default='Av. Principal, Edificio Sede Municipal, Valera, Edo. Trujillo')),
                ('telefono', models.CharField(default='0271-2310000 / 0414-0000000', max_length=100)),
                ('email', models.EmailField(default='contacto@alcaldia.gob.ve', max_length=254)),
                ('logo_principal', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_secundario', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Institución',
                'verbose_name_plural': 'Configuraciones de Institución',
            },
        ),
    ]
