# Generated by Django 6.0.6 on 2026-09-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracioninstitucion'),
        ('entregas', '0009_beneficioentregado_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudciudadano',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asociadas', to='entregas.beneficioentregado', verbose_name='Beneficio Entregado Asociado'),
        ),
        migrations.AddField(
            model_name='solicitudciudadano',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='solicitudciudadano',
            name='url_evidencia_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Evidencia 1'),
        ),
        migrations.AddField(
            model_name='solicitudciudadano',
            name='url_evidencia_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Evidencia 2'),
        ),
        migrations.AddField(
            model_name='solicitudciudadano',
            name='url_evidencia_3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Evidencia 3'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(default='Personalizado', max_length=100),
        ),
    ]
