# Generated by Django 6.0.6 on 2026-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioEntregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(max_length=100, unique=True)),
                ('cantidad_dada', models.IntegerField(default=0)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_prod', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_prod', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nombre_beneficiario', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url_evidencia', models.URLField(blank=True, max_length=500, null=True)),
                ('via', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
