# Generated by Django 6.0.6 on 2026-07-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficioentregado',
            old_name='url_evidencia',
            new_name='url_evidencia_1',
        ),
        migrations.AddField(
            model_name='beneficioentregado',
            name='url_evidencia_2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='beneficioentregado',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
