# Generated by Django 6.0.6 on 2026-07-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_rename_url_evidencia_beneficioentregado_url_evidencia_1_and_more'),
    ]

    operations = [
    ]
