# Generated by Django 6.0.6 on 2026-08-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_auto_20260726_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioentregado',
            name='firma_beneficiario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
