# Generated by Django 6.0.6 on 2026-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_beneficioentregado_firma_beneficiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioentregado',
            name='cedula',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beneficioentregado',
            name='codigo_prod',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficioentregado',
            name='fecha',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficioentregado',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
