# Generated by Django 6.0.6 on 2026-09-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0007_remove_formatobm4_contralor_usuario_and_more'),
        ('entregas', '0005_alter_beneficioentregado_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioentregado',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='SIA.sia_producto'),
        ),
    ]
