# Generated by Django 6.0.6 on 2026-09-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0006_beneficioentregado_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioentregado',
            name='huella_dactilar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
