# Generated by Django on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0007_beneficioentregado_huella_dactilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioentregado',
            name='url_evidencia_3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
