# Generated by Django 6.0.6 on 2026-09-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0008_beneficioentregado_url_evidencia_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioentregado',
            name='fecha_entrega',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Entrega'),
        ),
    ]
