# Generated by Django 6.0.6 on 2026-07-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beneficiario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beneficiario',
        ),
    ]
