# Generated by Django 6.0.6 on 2026-07-28 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_beneficiario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_receptor', models.CharField(max_length=150, verbose_name='Jefe / Persona Autorizada')),
                ('departamento_o_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_prod', models.CharField(max_length=255, verbose_name='Producto o Artículo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
