# Generated by Django 6.0.6 on 2026-07-30 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asignacionespecial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionespecial',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='asignacionespecial',
            name='descripcion_prod',
        ),
        migrations.RemoveField(
            model_name='asignacionespecial',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_presentacion',
            field=models.CharField(choices=[('unidad', 'Unidades Sueltas'), ('caja', 'Caja / Paquete / Bulto')], default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_empaque',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='asignacionespecial',
            name='departamento_o_cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionespecial',
            name='nombre_receptor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='almacen',
            field=models.CharField(default='Principal', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='SIA_producto',
        ),
        migrations.CreateModel(
            name='DetalleAsignacionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_prod', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.asignacionespecial')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
