# Generated by Django 6.0.6 on 2026-07-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_asignacionespecial_cantidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
