# Generated by Django 6.0.6 on 2026-07-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIA_producto',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SIA_producto',
            },
        ),
    ]
