# Generated by Django 6.0.6 on 2026-07-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0001_initial'),
    ]

    operations = [
    ]
