# Generated by Django 6.0.6 on 2026-07-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0002_auto_20260730_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sia_producto',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='tipo_presentacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='unidades_por_empaque',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='almacen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
