# Generated by Django 6.0.6 on 2026-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0003_sia_producto_id_sia_producto_tipo_presentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sia_producto',
            name='almacen',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
