# Generated by Django 6.0.6 on 2026-08-04 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0004_alter_sia_producto_almacen_alter_sia_producto_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nro_guia_o_acta', models.CharField(blank=True, max_length=100, null=True)),
                ('origen_o_proveedor', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingresada', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.sia_producto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='SIA.entradainventario')),
            ],
        ),
    ]
