# Generated by Django 6.0.6 on 2026-08-18 23:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0005_entradainventario_detalleentradainventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sia_producto',
            options={'verbose_name': 'Bien / Producto de Inventario', 'verbose_name_plural': 'Bienes y Productos de Inventario'},
        ),
        migrations.AddField(
            model_name='entradainventario',
            name='rif_proveedor',
            field=models.CharField(default='G-20000001-9', max_length=20),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='costo_adquisicion_ves',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='cui_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Código Único de Inventario (CUI)'),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='custodio_cedula',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='custodio_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='estado_conservacion',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deteriorado', 'Deteriorado'), ('Inservible', 'Inservible')], default='Excelente', max_length=20),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='estado_venezuela',
            field=models.CharField(default='Distrito Capital', max_length=100),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='estatus_sudebip',
            field=models.CharField(choices=[('Activo', 'Activo (Incorporado BM-1)'), ('En Proceso Baja', 'En Proceso de Desincorporación (BM-4)'), ('Desincorporado', 'Desincorporado Definitivo')], db_index=True, default='Activo', max_length=25),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='fecha_adquisicion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='grupo_cuben',
            field=models.CharField(db_index=True, default='01', max_length=20, verbose_name='Grupo CUBEN (SUDEBIP)'),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='serial_fabrica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='valor_rescate_ves',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sia_producto',
            name='vida_util_anos',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='FormatoBM4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente_nro', models.CharField(db_index=True, max_length=50, unique=True)),
                ('causal_desincorporacion', models.CharField(max_length=100)),
                ('informe_tecnico_detalles', models.TextField()),
                ('fecha_aval_contraloria', models.DateTimeField(blank=True, null=True)),
                ('estatus_contraloria', models.CharField(choices=[('Pendiente', 'Pendiente Aval Fiscal'), ('Avalado', 'Avalado por Contraloría Interna / CGR'), ('Rechazado', 'Rechazado en Auditoría')], db_index=True, default='Pendiente', max_length=20)),
                ('dictamen_sudebip_nro', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_firmado_suscerte', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('contralor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm4_avalados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_bm4', to='SIA.sia_producto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm4_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente Desincorporación BM-4',
                'verbose_name_plural': 'Expedientes Desincorporación BM-4',
                'ordering': ['-timestamp_creacion'],
            },
        ),
    ]
