# Generated by Django 6.0.6 on 2026-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0006_alter_sia_producto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatobm4',
            name='contralor_usuario',
        ),
        migrations.RemoveField(
            model_name='formatobm4',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='formatobm4',
            name='registrado_por',
        ),
        migrations.AlterModelOptions(
            name='sia_producto',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='costo_adquisicion_ves',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='cui_codigo',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='custodio_cedula',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='custodio_nombre',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='estado_conservacion',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='estado_venezuela',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='estatus_sudebip',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='fecha_adquisicion',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='grupo_cuben',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='serial_fabrica',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='ubicacion_fisica',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='valor_rescate_ves',
        ),
        migrations.RemoveField(
            model_name='sia_producto',
            name='vida_util_anos',
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='nro_guia_o_acta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NÂ° GuÃ\xada / Acta de RecepciÃ³n'),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='origen_o_proveedor',
            field=models.CharField(max_length=255, verbose_name='Proveedor / Origen'),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='rif_proveedor',
            field=models.CharField(default='G-20000001-9', max_length=20, verbose_name='RIF del Proveedor'),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='almacen',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Almacen'),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='tipo_presentacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo/Presentacion'),
        ),
        migrations.AlterField(
            model_name='sia_producto',
            name='unidades_por_empaque',
            field=models.IntegerField(default=1, verbose_name='Unidades por Empaque'),
        ),
        migrations.AddConstraint(
            model_name='sia_producto',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='sia_producto_cantidad_no_negativa'),
        ),
        migrations.DeleteModel(
            name='FormatoBM4',
        ),
    ]
