# Generated by Django 6.0.6 on 2026-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('cedula', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
